name: Node.js CI

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint
