name: Check H5P library version

on:
  pull_request:
    types:
      - opened # PR opens
      - labeled # PR is labeled
      - unlabeled # A label is removed from PR
      - synchronize # A commit is added - i.e. the PR's code is changed

env:
  working-directory: .
  project-id: h5p-editor-uuid
  project-name: H5PEditor.UUIDWidget

jobs:
  check-h5p-library-version:
    name: Check H5P if library version is updated
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check library version
        uses: boyum/comment-h5p-library-version-action@v2 # https://github.com/boyum/comment-h5p-library-version-action
        with:
          working-directory: ${{env.working-directory}}
          project-id: ${{env.project-id}}
          cancel-label: non-functional
          version-changed-message: |
            :tada: \`${{ env.project-name }}\`'s library version was updated from **%OLD_VERSION%** to **%NEW_VERSION%**.
          version-not-changed-message: |
            :warning: \`${{ env.project-name }}\`'s library version was not updated.
            Add the label \`%CANCEL_LABEL%\` if this PR does not require a change of version numbers.

            **Current version:** %NEW_VERSION%
            **Main version:** %OLD_VERSION%
